### ISSUE TITLE
404

### ISSUE THREAD

**Issue by DominikAngerer** [technologieplauscherl/technologieplauscherl.github.io#66]
Da gibts wohl nen issue.

![404 on Techplauscherl](https://a.storyblok.com/f/39849/b68dad83e6/bildschirmfoto-2017-02-02-um-13-30-42.png)

#ohne_www_ist_das_internet_kein_internet
#wwwonly

**Comment by onefriendaday** [comment]
just point the a record to http://wwwizer.com/.

**Comment by ddprrt** [comment]
Ähm whot?
#doesnotworkonyourmachine

**Comment by saxx** [comment]
@ddprrt Evtl. ein Problem wegen der CloudFlare-Umstellung heute morgen? Der DNS zeigt nun nicht mehr auf CloudFront, sondern direkt (CNAME) auch technologieplauscherl.github.io. Deswegen gehts bei dir, wie bei mir, auch noch (DNS TTL).

Kann es sein, dass noch Config bei Github Pages fehlt?

**Comment by saxx** [comment]
I just added missing domain configuration for github pages. Hope this solves the issue. Please note that we had a 2 day TTL on the DNS, so it could take a while until it works everywhere.

**Comment by onefriendaday** [comment]
No. now it's not working at all. www is redirecting to without www. ERR_TOO_MANY_REDIRECTS.

So far as I know cloudflare doesn't allow you create cnames on naket domains with ssl. so the easiest way to fix this issue would be to point the a-record without www to 174.129.25.170

**Comment by saxx** [comment]
Thanks. Afaik Cloudflare does support CNAME flattening (so this should not be a problem), but just to make sure I switched to A record just now.

Hopefully this fixes the problem ... I don't understand completely tho, because it's a redirect loop http > https > http > https ... and I'm not really sure where this comes from.

**Comment by saxx** [comment]
Hmm, not entirely sure but it seems that the previous cloudfront setup is still funkying things up in regard to the redirect loop. I still get `X-Cache:Redirect from cloudfront` stuff in my HTTP headers. Can this be right? If so, I'd suggest waiting a few hours and hope it resolves itself.

**Comment by onefriendaday** [comment]
Are you using cloudfront or cloudflare? You wrote cloudflare above and now you write X-Cache:Redirect from cloudfront.

Could you please post a screenshot of the settings?
I suggest you to setup the naked domain with a A-Record to 174.129.25.170 so you get redirected to www.technologieplauscherl.com which should then be a CNAME to the github page.

**Comment by saxx** [comment]
This morning we switched form CloudFront to CloudFlare, because our own SSL cert has been revoked by Mozilla. CloudFront had a TTL setting of two days.

Current setup:
- Nameservers point to CloudFlare
- CloudFlare A record points to the IPs mentioned in https://help.github.com/articles/setting-up-an-apex-domain/
- CNAME for www points to @
- Custom domain on GitHub is configured for technologieplauscherl.at

Please let me know if anything looks wrong to you.

**Comment by saxx** [comment]
Problem was, as suspected, still with CloudFront (where we missed something). All is well.
